name: bloc_project_structure
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons is used for ios icons.
  cupertino_icons: ^1.0.2

  # A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
  flutter_bloc: ^8.1.1

  # Easily configure any flutter application with global variables using a `.env` file.
  flutter_dotenv: ^5.0.2

  # A Flutter plugin to use the Firebase Core API, which enables connecting to multiple Firebase apps.
  firebase_core: ^2.3.0

  # A cross platform plugin for displaying push notification in firebase.
  firebase_messaging: ^14.1.1

  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^9.4.0

  # This package contains a set of high-level functions and classes that make it easy to consume HTTP resources. It's multi-platform, and supports mobile, desktop, and the browser.
  http: ^0.13.5

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and
  # to access the concrete implementation from everywhere in your App.
  get_it: ^7.2.0

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text,
  # and other internationalization issues.
  intl: ^0.17.0

  # Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.0.15

  # A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^4.0.6

  # Automatically generate code for converting to and from JSON by annotating Dart classes.

  json_annotation: ^4.7.0

  # RxDart is an implementation of the popular reactiveX api for asynchronous programming, leveraging the native Dart Streams api.
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .config
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
